apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: multi-tenant-virtualservice-sourcelabels
spec:
  hosts:
    - multi-tenant-service.default.svc.cluster.local
  gateways:
    - mesh
    - multi-tenant-gateway
  http:
    - match:
        - sourceLabels:
            app: sleep
            version: v1
      route:
        - destination:
            host: multi-tenant-service.default.svc.cluster.local
            subset: v2
      timeout: 3s
      retries:
        attempts: 2
        perTryTimeout: 1s
        retryOn: "5xx"
    - route:
        - destination:
            host: multi-tenant-service.default.svc.cluster.local
            subset: v1
      timeout: 3s
      retries:
        attempts: 2
        perTryTimeout: 1s
        retryOn: "5xx"