apiVersion: v1
kind: Endpoints
metadata:
  name: registry-endpoint
subsets:
  - addresses:
      - ip: 192.168.2.200
    ports:
      - port: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: registry-endpoint
spec:
  clusterIP: 10.1.218.158
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP